version: "{build}"

branches:
  only:
    - master

build: off

install:
  - choco install jdk10 -params 'installdir=c:\\jdk10'
  - SET JAVA_HOME=c:\\jdk10
  - SET PATH=c:\\jdk10\bin;%PATH%

test_script:
  - mvn clean package

